In [1]:
with open('day_13.txt') as f:
    inputs = f.read()
    coords, instructions = inputs.split('\n\n')
    
#splits up the coordinates and the instructions into two lists
coords = [[int(i) for i in i.strip().split(',')] for i in coords.split('\n')]
instructions = instructions.split('\n')

In [2]:
#initial setup for our paper
coords = np.array(coords)
y_max = coords[:,1].max()+1 #grid width
x_max = coords[:,0].max()+1 #grid height
paper = np.zeros((y_max, x_max))

#sets all of the starting "dots"
paper[coords[:,1], coords[:,0]] = 1

In [3]:
def fold_y(coord, paper):
    y_max, x_max = paper.shape[0], paper.shape[1]
    folded = np.zeros((coord, x_max))
    dist = y_max - coord - 1
    print(' ------------ ORIGINAL ------------ \n',paper)
#     print('\ncoord = {}, dist = {}, y_max = {}, x_max = {}'.format(coord, dist, y_max, x_max))
#  top of folded part     top half of paper          bottom half of paper
    folded[-dist:,] = paper[coord-dist:coord,:] + np.flipud(paper[coord+1:,:])
    print('\n ------- FOLDED ALONG Y={} -------\n{}\n'.format(coord, np.minimum(1,folded)))
    return np.minimum(1,folded)

def fold_x(coord, paper):
    y_max, x_max = paper.shape[0], paper.shape[1]
    folded = np.zeros((y_max, coord))
    dist = x_max - coord - 1
    print(' ------------ ORIGINAL ------------ \n',paper)
#     print('\ncoord = {}, dist = {}, y_max = {}, x_max = {}'.format(coord, dist, y_max, x_max))
#  left of folded part   left half of paper         right half of paper
    folded[:,-dist:] = paper[:,coord-dist:coord] + np.fliplr(paper[:,coord+1:])
    print('\n ------- FOLDED ALONG X={} -------\n{}\n'.format(coord, np.minimum(1,folded)))
    return np.minimum(1,folded)

In [4]:
for i, instr in enumerate (instructions):
    info = instr.split(' ')[-1]
    ax, coord = info.split('=')
    if ax == 'y':
        paper = fold_y(int(coord), paper)
    if ax == 'x':
        paper = fold_x(int(coord), paper)
    if i == 0: #answer for part 1
        print('After 1st fold: {}'.format(int(paper.sum())))

#converts 1's & 0's to a more readable format (part 2)
paper = paper.astype(int).astype(str)
total = ["".join(paper[i,:]) for i in range(paper.shape[0])]
print("\n".join(total).replace("1", "#").replace("0"," "))

 ------------ ORIGINAL ------------ 
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

 ------- FOLDED ALONG X=655 -------
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

After 1st fold: 638
 ------------ ORIGINAL ------------ 
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

 ------- FOLDED ALONG Y=447 -------
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

 ------------ ORIGINAL ------------ 
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

 ------- 